---
apiVersion: v1
name: cert-manager-webhook-selectel
appVersion: "1.2.5"
description: Selectel DNS cert-manager ACME webhook
maintainers:
  - name: andrsp
    email: izotikov@selectel.ru
    url: https://github.com/andrsp
version: 1.2.5
